services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "3002:3002"
    command: "yarn develop"
    image: ed/canvas-practise-2
    volumes:
      - ./:/app
      - /app/node_modules/
    environment:
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://baconsnake.universlabs.io:3002